### ISSUE TITLE
初次安装预览提示main.css错误

### ISSUE THREAD

**Issue by wxlost** [DIYgod/hexo-theme-sagiri#2]
ERROR Asset render failed: css/main.css
Error: /home/blog/themes/sagiri/source/css/main.styl:47:9
   43| // Custom Layer
   44| // --------------------------------------------------
   45| @import "_custom/custom";
   46| 
   47| @import "../../node_modules/nprogress/nprogress.css"
---------------^
   48| 
   49| #nprogress .bar {
   50|   background: #97dffd;

failed to locate @import file ../../node_modules/nprogress/nprogress.css

    at Evaluator.visitImport (/home/blog/node_modules/stylus/lib/visitor/evaluator.js:915:21)
    at Evaluator.Visitor.visit (/home/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/home/blog/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/home/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.evaluate (/home/blog/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/home/blog/node_modules/stylus/lib/renderer.js:86:26)
    at Hexo.module.exports (/home/blog/node_modules/hexo-renderer-stylus/lib/renderer.js:53:6)
    at Hexo.tryCatcher (/home/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/root/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/home/blog/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/home/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)

**Comment by wxlost** [comment]
npm install --save nprogress
npm install balloon-css
均已运行

**Comment by DIYgod** [comment]
需要在主题目录下执行 npm install
